apiVersion: v1
kind: Service
metadata:
  name: paas-kustomize
  labels:
    app: paas-kustomize
spec:
  selector:
    app: paas-kustomize
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 8080-tcp